packages:
  - 'functions'
  - '.'

excludeDirectories:
  - 'node_modules'
  - 'dist'
  - 'build'
  - 'coverage'
  - 'logs'
  - 'tmp'
  - 'cache'
  - 'temp'
  - 'functions'
  - 'firebase-config.json'
  - 'dawn-naglich-firebase.json'

onlyBuiltDependencies:
  - '@firebase/util'
  - protobufjs
  - unrs-resolver
